INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date)

